trigger:
  branches:
    include:
    - none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0  # Required for SonarCloud Git history

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'unit-testing-using-dotnet-test.sln'

# EXACT SonarCloudPrepare from docs (with your project details)
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'ravikumar-cybage'
    scannerMode: 'dotnet'
    projectKey: 'ravikumar-cybage_finance-service'  # YOUR project key
    projectName: 'finance-service'
    extraProperties: |
      # Disable Multi-Language analysis (from docs)
      sonar.scanner.scanAll=false
      # EXACT PATH from docs pattern
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/SonarCloud/results/coverage.opencover.xml

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'unit-testing-using-dotnet-test.sln'

# EXACT test command from docs
- task: DotNetCoreCLI@2
  displayName: 'Test with Coverage'
  inputs:
    command: 'test'
    projects: 'SonarCloud/PrimeService.Tests.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutput=results/coverage'

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'

# ------------------------------------
# SonarCloud Publish
# ------------------------------------
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'

- task: PublishCodeCoverageResults@2
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: 'Cobertura'   # required
    summaryFileLocation: '$(Build.SourcesDirectory)/SonarCloud/Tests/results/coverage.opencover.xml'
    failIfCoverageEmpty: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Coverage Files'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/SonarCloud/Tests/results'
    ArtifactName: 'CodeCoverage'
    publishLocation: 'Container'
