trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: MIS-DOCKER-RK

steps:
- checkout: self
  fetchDepth: 0

# Restore all projects in solution
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'unit-testing-using-dotnet-test.sln'

# Prepare SonarCloud analysis
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarCloud'  # Update with your service connection name
    organization: 'ravikumar-cybage'  # Update with your SonarCloud org
    scannerMode: 'dotnet'
    projectKey: 'ravikumar-cybage'  # Update with your SonarCloud project key
    projectName: 'PrimeService Demo'
    extraProperties: |
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml

# Build solution
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'unit-testing-using-dotnet-test.sln'
    arguments: '--configuration $(Configuration)'

# Run tests with coverage collection
- task: DotNetCoreCLI@2
  displayName: 'Test with Coverage'
  inputs:
    command: 'test'
    projects: 'PrimeService.Tests/PrimeService.Tests.csproj'
    arguments: >
      --configuration $(Configuration)
      --collect:"XPlat Code Coverage"
      --results-directory $(Build.SourcesDirectory)/coverage

# Debug: List coverage files
- task: Bash@3
  displayName: 'List coverage files'
  inputs:
    targetType: 'inline'
    script: |
      find $(Build.SourcesDirectory) -name "*coverage*" -type f -o -name "*.xml" | head -20

# Run SonarCloud analysis
- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

# Wait for SonarCloud quality gate
- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'

# Publish coverage to Azure Pipelines
- task: PublishCodeCoverageResults@2
  displayName: 'Publish coverage results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/**/*.cobertura.xml'
    failIfCoverageEmpty: false
    reportDirectory: '$(Build.SourcesDirectory)/coverage/**/TestResults'
