# trigger:
#   branches:
#     include:
#     - none

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - checkout: self
#   fetchDepth: 0  # Required for SonarCloud Git history
# - task: UseDotNet@2
#   inputs:
#     packageType: 'sdk'
#     version: '8.0.x'
# - task: DotNetCoreCLI@2
#   displayName: 'Restore'
#   inputs:
#     command: 'restore'
#     projects: 'unit-testing-using-dotnet-test.sln'

# # EXACT SonarCloudPrepare from docs (with your project details)
# # - task: SonarCloudPrepare@3
# #   inputs:
# #     SonarCloud: 'SonarCloud'
# #     organization: 'ravikumar-cybage'
# #     scannerMode: 'dotnet'
# #     projectKey: 'ravikumar-cybage_finance-service'  # YOUR project key
# #     projectName: 'finance-service'
# #     extraProperties: |
# #       # Disable Multi-Language analysis (from docs)
# #       sonar.scanner.scanAll=false
# #       # EXACT PATH from docs pattern
# #       sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/PrimeService.Tests/results/coverage.opencover.xml
# - task: SonarCloudPrepare@3
#   inputs:
#     SonarCloud: 'SonarCloud'
#     organization: 'ravikumar-cybage'
#     scannerMode: 'dotnet'
#     projectKey: 'ravikumar-cybage_finance-service'
#     projectName: 'finance-service'
#     extraProperties: |
#       sonar.scanner.scanAll=false
#       sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/PrimeService.Tests/results/coverage.opencover.xml
#       # FORCE EXACT MATCH CONFIGURATION
#       sonar.coverage.exclusions=**/*Tests*/**
#       sonar.scm.disabled=false
#       sonar.cs.vstest.reportsPaths=$(Build.SourcesDirectory)/PrimeService.Tests/results/coverage.cobertura.xml

# - task: DotNetCoreCLI@2
#   displayName: 'Build'
#   inputs:
#     command: 'build'
#     projects: 'unit-testing-using-dotnet-test.sln'
#     arguments: '--configuration Release'

# # EXACT test command from docs
# - task: DotNetCoreCLI@2
#   displayName: 'Test with Coverage'
#   inputs:
#     command: 'test'
#     projects: 'PrimeService.Tests/PrimeService.Tests.csproj'
#     arguments: '--configuration Release /p:CollectCoverage=true /p:CoverletOutput=results/coverage /p:CoverletOutputFormat=opencover'
#     publishTestResults: true
#   continueOnError: true

# - task: SonarCloudAnalyze@3
#   inputs:
#     jdkversion: 'JAVA_HOME_17_X64'

# - task: SonarCloudPublish@3
#   inputs:
#     pollingTimeoutSec: '300'

# - task: PublishCodeCoverageResults@2
#   displayName: 'Publish Code Coverage Results'
#   inputs:
#     codeCoverageTool: 'Cobertura'   # required
#     summaryFileLocation: '$(Build.SourcesDirectory)/PrimeService.Tests/results/coverage.opencover.xml'
#     failIfCoverageEmpty: true

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Coverage Files'
#   inputs:
#     PathtoPublish: '$(Build.SourcesDirectory)/PrimeService.Tests/results'
#     ArtifactName: 'CodeCoverage'
#     publishLocation: 'Container'
trigger:
  branches:
    include:
    - none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'unit-testing-using-dotnet-test.sln'

# ✅ FIXED SonarCloudPrepare - SINGLE format only
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'ravikumar-cybage'
    scannerMode: 'dotnet'
    projectKey: 'ravikumar-cybage_finance-service'
    projectName: 'finance-service'
    extraProperties: |
      sonar.scanner.scanAll=false
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/PrimeService.Tests/**/coverage.opencover.xml
      sonar.coverage.exclusions=**/*Tests*/**

# ✅ FIXED Build
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'unit-testing-using-dotnet-test.sln'
    arguments: '--configuration Release'

# ✅ FIXED Test - CORRECT Coverlet syntax + working directory
- task: DotNetCoreCLI@2
  displayName: 'Test with Coverage'
  inputs:
    command: 'test'
    projects: 'PrimeService.Tests/PrimeService.Tests.csproj'
    arguments: '--no-fail --configuration Release --collect:"XPlat Code Coverage" --logger trx --results-directory ./coverage'
  continueOnError: true

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'

# ✅ FIXED Coverage publish - correct path + format
- task: PublishCodeCoverageResults@2
  displayName: 'Publish Code Coverage'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/PrimeService.Tests/coverage/coverage.cobertura.xml'
    failTaskOnFailedTests: false
