trigger:
  branches:
    include:
    - none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0  # Required for SonarCloud Git history

# Package management (automates the dotnet remove/add)
- task: DotNetCoreCLI@2
  displayName: 'Remove coverlet.collector'
  inputs:
    command: 'custom'
    custom: 'remove package coverlet.collector --project PrimeService.Tests/PrimeService.Tests.csproj'
  continueOnError: true

- task: DotNetCoreCLI@2
  displayName: 'Add coverlet.msbuild'
  inputs:
    command: 'custom'
    custom: 'add package coverlet.msbuild --project PrimeService.Tests/PrimeService.Tests.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'unit-testing-using-dotnet-test.sln'

# EXACT SonarCloudPrepare from docs (with your project details)
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'ravikumar-cybage'
    scannerMode: 'dotnet'
    projectKey: 'ravikumar-cybage_finance-service'  # YOUR project key
    projectName: 'finance-service'
    extraProperties: |
      # Disable Multi-Language analysis (from docs)
      sonar.scanner.scanAll=false
      # EXACT PATH from docs pattern
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/PrimeService.Tests/results/coverage.opencover.xml

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'unit-testing-using-dotnet-test.sln'

# EXACT test command from docs
- task: DotNetCoreCLI@2
  displayName: 'Test with Coverage'
  inputs:
    command: 'test'
    projects: 'PrimeService.Tests/PrimeService.Tests.csproj'
    arguments: '/p:CollectCoverage=true /p:CoverletOutput=results/coverage'

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'

# EXACT Azure coverage from docs
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '$(Build.SourcesDirectory)/PrimeService.Tests/results/coverage.cobertura.xml'
    failIfCoverageEmpty: true
